language: go

sudo: false

go:
    - 1.2
    - 1.3
    - tip

env:
    - ORIGINS_DISPATCH_NEO4J_URI="http://localhost:7474/db/data/"

before_install:
    - sh test/start-neo4j.sh

before_script:
    - go get ./...

script:
    - go test -v ./...
